spring:
  application.name: tdd-java

  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true